name: workflow2
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: display first message
      - run: echo "first steps"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: multi line command
      - run: echo "ok"
