name: workflow 2
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: display first message
      - run: echo "first steps"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: multi line command
      - run: echo "ok"
